# Generated by Django 5.0.4 on 2024-04-29 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20240429_1407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcontributor',
            old_name='contributions',
            new_name='contribution',
        ),
    ]
